package com.scaler.core.java_3_advance_3.dsa_30_problems_on_stacks_and_queues_and_deque;

import java.util.LinkedList;
import java.util.Queue;

/**
 * @author Deepak Kumar Rai
 * @created 31/10/23
 * @project scaler_course_code
 */
public class Q1_Generate_K_th_Palindrome {
    /**
     * Print the k th Palindrome Number generated by 1 and 2.
     * **/
    private static void printTheKthPalindromeNumber(int K) {
        Queue<String> queue = new LinkedList<>();
        queue.add("1");
        queue.add("2");
        for (int i = 1; i < K; i++) {
            String element = queue.poll();
            assert element != null;
            int N = element.length();
            String startToMid = element.substring(0, N / 2);
            if ((N & 1) == 0) {
                String midToEnd = element.substring(N / 2);
                queue.add(startToMid + "1" + midToEnd);
                queue.add(startToMid + "2" + midToEnd);
            } else if (!startToMid.equalsIgnoreCase("")) {
                char mid = element.charAt(N / 2);
                String afterMidToEnd = element.substring(N / 2 + 1);
                queue.add(startToMid + mid + mid + afterMidToEnd);
            } else {
                queue.add(element + element);
            }
        }
        System.out.println(K + "th palindrome: "+ queue.peek());
    }
    public static void main(String[] args) {
        int K = 10;
        printTheKthPalindromeNumber(K);
    }
}
